In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("BreastCancerWc_new.csv")
df

,code number,clump thickness,uniformity in cell size,uniformity in cell shape,marginal adhesion,single epi size,bare nuclei,bland chromatin,normal nucleoli,mitoses,class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2,1,1,1,2
695,841769,2,1,1,1,2,1,1,1,1,2
696,888820,5,10,10,3,7,3,8,10,2,4
697,897471,4,8,6,4,3,4,10,6,1,4
698,897471,4,8,8,5,4,5,10,4,1,4

In [3]:
df.dropna()

,code number,clump thickness,uniformity in cell size,uniformity in cell shape,marginal adhesion,single epi size,bare nuclei,bland chromatin,normal nucleoli,mitoses,class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2,1,1,1,2
695,841769,2,1,1,1,2,1,1,1,1,2
696,888820,5,10,10,3,7,3,8,10,2,4
697,897471,4,8,6,4,3,4,10,6,1,4
698,897471,4,8,8,5,4,5,10,4,1,4

In [4]:
df.isnull().sum()

code number                 0
clump thickness             0
uniformity in cell size     0
uniformity in cell shape    0
marginal adhesion           0
single epi size             0
bare nuclei                 0
bland chromatin             0
normal nucleoli             0
mitoses                     0
class                       0
dtype: int64

In [5]:
df['class'].value_counts()

2    458
4    241
Name: class, dtype: int64

In [6]:
def outliers(df_out, drop=False):
    for feature in df_out.columns:
        feature_data = df_out[feature]
        q1 = np.percentile(feature_data,25.)
        q3 = np.percentile(feature_data,75.)
        iqr = q3-1
        step = iqr*1.5
        outliers = feature_data[~((feature_data>=q1-step)&(feature_data<=q3+step))].index.tolist()
        if not drop:
            print(f"feature: {feature} , No. of outliers: {len(outliers)}")
        if drop:
            df.drop(outliers, inplace=True,errors='ignore')
            print(f"outliers from {feature} are removed.")

In [7]:
feature_list = ['clump thickness','uniformity in cell size','uniformity in cell shape','single epi size']

In [8]:
df.columns

Index(['code number', 'clump thickness', 'uniformity in cell size',
       'uniformity in cell shape', 'marginal adhesion', 'single epi size',
       'bare nuclei', 'bland chromatin', 'normal nucleoli', 'mitoses',
       'class'],
      dtype='object')

In [9]:
outliers(df[feature_list])

feature: clump thickness , No. of outliers: 0
feature: uniformity in cell size , No. of outliers: 0
feature: uniformity in cell shape , No. of outliers: 0
feature: single epi size , No. of outliers: 33

In [10]:
outliers(df[feature_list],drop=True)

outliers from clump thickness are removed.
outliers from uniformity in cell size are removed.
outliers from uniformity in cell shape are removed.
outliers from single epi size are removed.

In [11]:
df

,code number,clump thickness,uniformity in cell size,uniformity in cell shape,marginal adhesion,single epi size,bare nuclei,bland chromatin,normal nucleoli,mitoses,class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2,1,1,1,2
695,841769,2,1,1,1,2,1,1,1,1,2
696,888820,5,10,10,3,7,3,8,10,2,4
697,897471,4,8,6,4,3,4,10,6,1,4
698,897471,4,8,8,5,4,5,10,4,1,4

In [12]:
df["class"].unique()

array([2, 4], dtype=int64)

In [13]:
df = df.drop_duplicates()

In [14]:
df

,code number,clump thickness,uniformity in cell size,uniformity in cell shape,marginal adhesion,single epi size,bare nuclei,bland chromatin,normal nucleoli,mitoses,class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2,1,1,1,2
695,841769,2,1,1,1,2,1,1,1,1,2
696,888820,5,10,10,3,7,3,8,10,2,4
697,897471,4,8,6,4,3,4,10,6,1,4
698,897471,4,8,8,5,4,5,10,4,1,4

### Naive Bayes

In [15]:
from sklearn.preprocessing import LabelEncoder
labelenc = LabelEncoder()
for feature in df.columns:
    df[feature] = labelenc.fit_transform(df[feature])

C:\Users\Riya\AppData\Local\Temp\ipykernel_15172\1962537424.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature] = labelenc.fit_transform(df[feature])

In [16]:
X = df.drop(['class'],axis=1).values
y = df['class']

In [17]:
from sklearn.naive_bayes import MultinomialNB
multinom = MultinomialNB()

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=41)

In [19]:
multinom.fit(X_train,y_train)

MultinomialNB()

In [20]:
y_pred = multinom.predict(X_test)

In [21]:
from sklearn import metrics
print("1. Accuracy Score", metrics.accuracy_score(y_test,y_pred)*100)
print("2. Precision Score:",metrics.precision_score(y_test, y_pred))
print("3. Recall Score:", metrics.recall_score(y_test, y_pred))
print("4. f1 Score:", metrics.f1_score(y_test, y_pred))

1. Accuracy Score 89.0909090909091
2. Precision Score: 0.7887323943661971
3. Recall Score: 0.9491525423728814
4. f1 Score: 0.8615384615384616

In [22]:
from sklearn.linear_model import LogisticRegression
logistic= LogisticRegression()
logistic.fit(X_train,y_train)

C:\Users\Riya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [23]:
y_pred1=logistic.predict(X_test)

In [24]:
from sklearn import metrics
print("1. Accuracy Score", metrics.accuracy_score(y_test,y_pred1)*100)
print("2. Precision Score:",metrics.precision_score(y_test, y_pred1))
print("3. Recall Score:", metrics.recall_score(y_test, y_pred1))
print("4. f1 Score:", metrics.f1_score(y_test, y_pred1))

1. Accuracy Score 94.54545454545455
2. Precision Score: 0.9166666666666666
3. Recall Score: 0.9322033898305084
4. f1 Score: 0.9243697478991596